(function(){
'use strict';
const bank=window.STUDY_BANK,E=window.StudyEngine,by=id=>document.getElementById(id),KEY='mrs-knox-ea-study-2026-v1';
let state={selected:[],options:{},queue:[],history:[],completed:0,current:null},tick=null,endAt=null,remaining=0;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{by('storage-note').hidden=false;}}
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.selected)){state={...state,...saved};state.selected=[...new Set(state.selected.filter(id=>bank.subjects.some(s=>s.id===id)))];state.options=state.options&&typeof state.options==='object'?state.options:{};state.queue=Array.isArray(state.queue)?state.queue:[];state.history=Array.isArray(state.history)?state.history.filter(x=>x&&typeof x.subject==='string'):[];state.completed=Number.isFinite(state.completed)?state.completed:0;}}
catch{by('storage-note').hidden=false;}
function validSetup(){return state.selected.length&&state.selected.every(id=>{const s=bank.subjects.find(s=>s.id===id);if(!s.option)return true;if(s.option.text)return Boolean(String(state.options[id]||'').trim());return s.option.values.includes(state.options[id]);});}
state.active=Array.isArray(state.active)?E.activeSubjects(state):[...new Set([state.current?.subject,...state.selected].filter(id=>state.selected.includes(id)))].slice(0,3);
if(state.current){const s=bank.subjects.find(s=>s.id===state.current.subject&&state.active.includes(s.id)),t=s&&E.eligible(s,state.options).find(t=>t.id===state.current.topic);state.current=t&&E.METHODS[t.kind].includes(state.current.method)?E.makeTask(s,t,state.current.method,state.options,state.current.minutes===5):null;}
function setup(){
by('setup').hidden=false;by('study').hidden=true;by('cancel-setup').hidden=!validSetup();by('subject-search').value='';by('setup-error').textContent='';
by('subject-list').replaceChildren();
const areas=[...new Set(bank.subjects.map(s=>s.area))].sort();
areas.forEach(area=>{const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=area;field.append(legend);
 bank.subjects.filter(s=>s.area===area).forEach(s=>{const wrap=document.createElement('div');wrap.dataset.subject=s.name.toLowerCase();const label=document.createElement('label');label.className='subject-label';const box=document.createElement('input');box.type='checkbox';box.name='subject';box.value=s.id;box.checked=state.selected.includes(s.id);label.append(box,document.createTextNode(s.name));wrap.append(label);
 if(s.option){const opt=document.createElement('div');opt.className='subject-options';opt.hidden=!box.checked;const l=document.createElement('label');l.htmlFor='option-'+s.id;l.textContent=s.option.label;const input=document.createElement(s.option.text?'input':'select');input.id=l.htmlFor;input.dataset.option=s.id;
  if(s.option.text){input.type='text';input.maxLength=150;input.placeholder='e.g. renewable energy in Germany';input.value=state.options[s.id]||'';}
  else{input.append(new Option('Select the option your school chose',''));s.option.values.forEach(v=>input.append(new Option(v,v)));input.value=state.options[s.id]||'';}
  opt.append(l,input);wrap.append(opt);box.addEventListener('change',()=>opt.hidden=!box.checked);
 }
 field.append(wrap);});by('subject-list').append(field);});
}
by('subject-search').addEventListener('input',event=>{const q=event.target.value.toLowerCase();by('subject-list').querySelectorAll('[data-subject]').forEach(el=>el.hidden=!el.dataset.subject.includes(q));by('subject-list').querySelectorAll('fieldset').forEach(el=>el.hidden=![...el.querySelectorAll('[data-subject]')].some(x=>!x.hidden));});
by('setup-form').addEventListener('submit',event=>{event.preventDefault();const ids=[...by('subject-list').querySelectorAll('input[name=subject]:checked')].map(x=>x.value),options={};if(!ids.length){by('setup-error').textContent='Tick at least one subject.';return;}
for(const id of ids){const s=bank.subjects.find(s=>s.id===id);if(s.option){const value=by('option-'+id).value.trim();if(!value||(!s.option.text&&!s.option.values.includes(value))){by('setup-error').textContent='Add '+s.option.label.toLowerCase()+' for '+s.name+'.';by('subject-search').value='';by('subject-search').dispatchEvent(new Event('input'));by('option-'+id).focus();return;}options[id]=value;}}
const changed=JSON.stringify(ids)!==JSON.stringify(state.selected)||JSON.stringify(options)!==JSON.stringify(state.options);state.selected=ids;state.options=options;state.active=state.active.filter(id=>ids.includes(id));if(changed){state.queue=[];state.current=null;if(!state.active.length)state.active=ids.slice(0,3);}save();showStudy();if(!state.current&&state.active.length)generate();});
function sessionPicker(){
by('session-subjects').replaceChildren(...state.selected.map(id=>{const s=bank.subjects.find(s=>s.id===id),label=document.createElement('label'),box=document.createElement('input');label.className='subject-label';box.type='checkbox';box.name='session-subject';box.value=id;box.checked=state.active.includes(id);label.append(box,document.createTextNode(s.name));box.addEventListener('change',()=>{const chosen=[...by('session-subjects').querySelectorAll('input:checked')].map(x=>x.value);if(chosen.length>3){box.checked=false;return;}state.active=chosen;state.queue=[];if(state.current&&!chosen.includes(state.current.subject)){stopTimer();state.current=null;}save();sessionPicker();if(!state.current){by('task').hidden=true;by('ready').hidden=false;}by('exam').hidden=true;[...by('session-subjects').querySelectorAll('input')].find(input=>input.value===id).focus();});return label;}));
const count=state.active.length;by('session-subjects').querySelectorAll('input').forEach(box=>box.disabled=count===3&&!box.checked);
by('session-status').textContent=count?count+' of 3 selected'+(count===3?' — untick a subject to choose another.':'.'):'Choose at least one subject to get a task.';
by('generate').disabled=!count;by('practice-exam').disabled=!count;
}
function showStudy(){by('setup').hidden=true;by('study').hidden=false;by('selected-summary').textContent='Your saved subjects: '+state.selected.map(id=>bank.subjects.find(s=>s.id===id).name).join(', ');sessionPicker();by('completion').textContent=state.completed?state.completed+' checked task'+(state.completed===1?'':'s')+' completed.':'';if(state.current&&state.active.includes(state.current.subject))renderTask();else{state.current=null;by('task').hidden=true;by('ready').hidden=false;}}
function generate(quick=false){stopTimer();state.current=E.next(bank,state,{quick});save();renderTask();}
function renderTask(){const t=state.current,s=bank.subjects.find(s=>s.id===t.subject);by('ready').hidden=true;by('task').hidden=false;by('task-meta').textContent=s.name+' · '+t.minutes+' minutes';by('task-title').textContent=t.title;by('task-method').textContent=t.label;by('task-materials').textContent=t.materials;by('task-steps').replaceChildren(...t.steps.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));by('task-check').textContent=t.check;by('task-finish').textContent=t.finish;by('task-help').textContent=t.help;by('practice-text').hidden=!t.practiceText;by('practice-text').textContent=t.practiceText||'';by('task-source').href=t.source;by('help').open=false;by('shorten').disabled=t.minutes===5;by('timer').textContent='';by('timer-toggle').textContent='Start timer';by('exam').hidden=true;}
function stopTimer(){if(tick)clearInterval(tick);tick=null;endAt=null;remaining=0;by('timer').textContent='';by('timer-toggle').textContent='Start timer';}
function updateTimer(){const seconds=Math.max(0,Math.ceil((endAt-Date.now())/1000));by('timer').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');if(seconds===0){clearInterval(tick);tick=null;endAt=null;remaining=0;by('timer').textContent='Time finished — check your work.';by('timer-toggle').textContent='Restart timer';}}
by('timer-toggle').addEventListener('click',()=>{if(tick){remaining=Math.max(0,endAt-Date.now());clearInterval(tick);tick=null;endAt=null;by('timer-toggle').textContent='Resume timer';}else{endAt=Date.now()+(remaining||state.current.minutes*60000);remaining=0;updateTimer();tick=setInterval(updateTimer,1000);by('timer-toggle').textContent='Pause timer';}});
by('generate').addEventListener('click',()=>generate());
by('skip').addEventListener('click',()=>generate());
by('done').addEventListener('click',()=>{stopTimer();state.completed++;state.current=null;save();showStudy();by('generate').focus();});
by('shorten').addEventListener('click',()=>{const old=state.current,s=bank.subjects.find(s=>s.id===old.subject),t=s.topics.find(t=>t.id===old.topic);stopTimer();state.current=E.makeTask(s,t,old.method,state.options,true);save();renderTask();});
by('edit-setup').addEventListener('click',()=>{stopTimer();setup();by('setup-title').scrollIntoView();});
by('cancel-setup').addEventListener('click',showStudy);
by('print').addEventListener('click',()=>window.print());
by('reset-progress').addEventListener('click',()=>{stopTimer();state.queue=[];state.history=[];state.completed=0;state.current=null;state.lastSubject=null;save();showStudy();by('reset-status').textContent='Progress cleared. Your subjects are still saved.';});
by('practice-exam').addEventListener('click',()=>{
 const s=bank.subjects.find(s=>s.id===E.shuffle(state.active)[0]);const exam=by('exam');exam.hidden=false;
 exam.innerHTML='<h3>'+esc(s.name)+' · Practice exam session</h3><p>'+esc(s.coverage)+'</p><p><strong>Use:</strong> the first teacher-approved EA practice paper in your class revision folder. If you do not have one, open the official QCAA archive below.</p><ol><li>Set aside '+s.planning+' minutes for '+(s.planning===5?'perusal':'planning')+' and '+s.working+' minutes of working time'+(s.papers===2?' for one paper. Complete the second paper in another session':'')+'.</li><li>Follow the instructions and equipment requirements for that paper.</li><li>Mark using its matching guide. Record three errors, correct them, and reattempt one without the solution.</li></ol><p><a href="'+esc(s.page)+'" target="_blank" rel="noopener">Official QCAA papers and marking guides</a></p><p class="small">The archive currently contains earlier-cohort papers. Content, selected texts and formats may differ in 2026. Use a teacher-approved paper for a current-format simulation; older papers are supplementary practice.</p><p>'+esc(s.note)+'</p><button id="close-exam">Close practice exam session</button>';
 by('close-exam').addEventListener('click',()=>exam.hidden=true);exam.scrollIntoView({block:'nearest'});
});
by('review-subject').replaceChildren(...bank.subjects.map(s=>new Option(s.name,s.id)));
by('bank-count').textContent=bank.subjects.length+' subjects/specialisations · '+bank.subjects.reduce((n,s)=>n+s.topics.length,0)+' specific content items · '+Object.keys(E.LABELS).length+' study activities';
by('attribution').textContent=bank.attribution;by('timetable').href=bank.timetable;
function review(){const s=bank.subjects.find(s=>s.id===by('review-subject').value),option=state.options[s.id]||(s.option?.values?.[0])||(s.option?.text?'your investigation topic':'');
by('review-content').innerHTML='<h3>'+esc(s.name)+'</h3><p>'+esc(s.coverage)+'</p><p class="small">'+esc(s.version)+' · Checked '+esc(bank.checked)+'</p>'+(s.note?'<p>'+esc(s.note)+'</p>':'')+'<p><a href="'+esc(s.syllabus)+'" target="_blank" rel="noopener">Official syllabus</a> · <a href="'+esc(s.page)+'" target="_blank" rel="noopener">QCAA subject resources</a></p><p>Preview examples below do not change student selections or progress. Text/topic placeholders use an illustrative selection if you have not saved one.</p><div>'+s.topics.map(t=>'<div class="review-topic"><strong>'+esc(t.title.replaceAll('{option}',t.option||option))+'</strong><p class="small">'+esc(t.unit==='EA'?'EA analysis skills':'Unit '+t.unit)+' · Focus: '+esc(t.focus.join(', '))+'</p><button class="sample-button" data-preview="'+esc(t.id)+'">See a sample task</button><div id="preview-'+esc(t.id)+'" hidden></div></div>').join('')+'</div>';
by('review-content').querySelectorAll('[data-preview]').forEach(button=>button.addEventListener('click',()=>{const t=s.topics.find(t=>t.id===button.dataset.preview),options={...state.options,[s.id]:t.option||option},task=E.makeTask(s,t,E.METHODS[t.kind][0],options),el=by('preview-'+t.id);el.hidden=!el.hidden;el.innerHTML='<p><strong>'+esc(task.label)+' · '+task.minutes+' minutes</strong></p><ol>'+task.steps.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol><p><strong>Check:</strong> '+esc(task.check)+'</p>'+(task.practiceText?'<p>'+esc(task.practiceText)+'</p>':'');}));}
by('review-subject').addEventListener('change',review);review();
if(validSetup())showStudy();else setup();
})();
