const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.resolve(__dirname,'../index.html'));
 assert.deepEqual(await page.locator('#subject-list legend').allTextContents(),['1. Select your English','2. Select your Maths','3. Select your electives']);
 await page.locator('input[value=english]').check();await page.locator('#option-english').selectOption('The Dry');
 await page.locator('input[value=maths_methods]').check();await page.locator('input[value=legal]').check();await page.locator('input[value=chemistry]').check();
 await page.locator('#setup-form button[type=submit]').click();
 assert.equal(await page.locator('#session-subjects input:checked').count(),3);
 assert.equal(await page.locator('#session-subjects input:disabled').count(),1);
 while(await page.locator('#session-subjects input:checked').count())await page.locator('#session-subjects input:checked').first().uncheck();
 await page.locator('#session-subjects input[value=english]').check();await page.locator('#generate').click();
 assert.equal(await page.locator('#task-subject').textContent(),'English');assert.match(await page.locator('#task-title').textContent(),/The Dry/);
 assert.equal(await page.locator('#resource-links a[href="https://www.litcharts.com/lit"]').count(),1);
 await page.reload();assert.equal(await page.locator('#task-subject').textContent(),'English');
 await page.locator('#session-subjects input[value=english]').uncheck();await page.locator('#session-subjects input[value=maths_methods]').check();await page.locator('#generate').click();
 assert.equal(await page.locator('#task-subject').textContent(),'Mathematical Methods');assert.equal(await page.locator('#resource-links a[href="https://www.khanacademy.org/math"]').count(),1);
 await page.locator('#session-subjects input[value=maths_methods]').uncheck();await page.locator('#session-subjects input[value=legal]').check();await page.locator('#generate').click();
 assert.equal(await page.locator('#task-subject').textContent(),'Legal Studies');assert.equal(await page.locator('#resource-links a[href*="legalaid"]').count(),1);
 await page.locator('#edit-setup').click();await page.locator('#subject-search').fill('legal');assert.equal(await page.locator('[data-subject]:visible').count(),1);await page.locator('#cancel-setup').click();
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:path.resolve(__dirname,'../../task-preview.png'),fullPage:true});
 const standalone=await browser.newPage();await standalone.goto('file://'+path.resolve(__dirname,'../EA_Study_Randomiser.html'));assert.equal(await standalone.locator('#subject-list input[name=subject]').count(),48);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: grouped setup, saved text, session limit, subject headings, relevant links, persistence, search, mobile width and standalone file.');
})().catch(e=>{console.error(e);process.exit(1)});
