const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),key='mrs-knox-ea-study-2026-v1',errors=[];
function load(saved){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://session.example/',runScripts:'outside-only',virtualConsole:vc});const w=d.window;w.HTMLElement.prototype.scrollIntoView=function(){};if(saved)w.localStorage.setItem(key,saved);for(const f of ['bank.js','engine.js','app.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));return w;}
let w=load();const $=q=>w.document.querySelector(q),$$=q=>[...w.document.querySelectorAll(q)],saved=()=>JSON.parse(w.localStorage.getItem(key));
function check(q,value=true){const e=$(q);e.checked=value;e.dispatchEvent(new w.Event('change'));}
function visibleSteps(){return $$('#subject-list fieldset').filter(x=>!x.hidden).map(x=>x.dataset.step);}
assert.deepEqual(visibleSteps(),['0']);check('input[value=english]');$('#setup-next').click();assert.deepEqual(visibleSteps(),['0']);assert($('#setup-error').textContent.includes('English'));
$('#option-english').value='The Dry';$('#setup-next').click();assert.deepEqual(visibleSteps(),['1']);check('input[value=maths_methods]');$('#setup-back').click();assert.equal($('#option-english').value,'The Dry');$('#setup-next').click();$('#setup-next').click();assert.deepEqual(visibleSteps(),['2']);check('input[value=legal]');check('input[value=chemistry]');$('#setup-save').click();assert.equal($('#session-config').hidden,false);assert.equal($('#task').hidden,true);
assert.equal($$('#session-subjects input:checked').length,3);assert.equal($$('#session-subjects input:disabled').length,1);
check('#session-subjects input[value=chemistry]',false);check('#session-subjects input[value=legal]');
$('#session-duration').value='10';$('#generate').click();assert($('#session-error').textContent.includes('five minutes'));assert.equal($('#task').hidden,true);
$('#session-duration').value='30';$('#session-mode').value='hard';$('#generate').click();assert.equal($('#session-config').hidden,true);assert.equal($('#task-meta').textContent,'10 minutes · Hard mode');assert.equal($('#task-steps').tagName,'UL');assert.equal($('#task-check').tagName,'UL');assert($('#task-intro').textContent.includes($('#task-title').textContent));assert.deepEqual(saved().session.blocks.map(b=>b.minutes),[10,10,10]);
const first=saved().current.topic;$('#skip').click();assert.equal(saved().session.index,0);assert.equal(saved().completed,0);assert.notEqual(saved().current.topic,first);
$('#shorten').click();assert.equal($('#task-meta').textContent,'10 minutes · Easy mode');assert($('#task-steps').textContent.includes('three key words'));
$('#done').click();assert.equal(saved().session.index,1);assert.equal($('#task-subject').textContent,'Mathematical Methods');assert.equal(saved().completed,1);
const stored=w.localStorage.getItem(key);w.close();w=load(stored);assert.equal(saved().session.index,1);assert.equal($('#task-subject').textContent,'Mathematical Methods');$('#done').click();assert.equal($('#task-subject').textContent,'Legal Studies');$('#done').click();assert.equal($('#task').hidden,true);assert.equal($('#ready').hidden,false);assert($('#ready-message').textContent.includes('3 task blocks'));assert.equal(saved().completed,3);
$('#new-session').click();assert.equal($('#session-config').hidden,false);assert.equal($('#session-mode').value,'hard');$('#session-mode').value='easy';$('#session-duration').value='45';$('#generate').click();assert.equal(saved().session.duration,45);assert.equal($('#task-meta').textContent,'15 minutes · Easy mode');$('#change-session').click();assert.equal(saved().session,null);assert.equal(saved().completed,3);w.close();
// Earlier versions' saved subjects and progress migrate to session setup.
w=load(JSON.stringify({selected:['legal'],options:{},active:['legal'],completed:7,history:[],current:{subject:'legal',topic:'obsolete',method:'recall'}}));assert.equal($('#session-config').hidden,false);assert.equal($('#task').hidden,true);assert.equal(saved().completed,7);assert($('#completion').textContent.includes('7'));w.close();
// Users without English or maths can progress to electives.
w=load();$('#setup-next').click();$('#setup-next').click();check('input[value=legal]');$('#setup-save').click();assert.deepEqual(saved().selected,['legal']);w.close();assert.deepEqual(errors,[]);
console.log('PASS: paged setup, option validation, Back, elective-only setup, session controls, exact blocks, mode support, swapping, completion, reload and migration.');
